#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

use function cli\line;
use function cli\prompt;
use function BrainGames\Engine\greetUser;
use function BrainGames\Engine\askQuestion;
use function BrainGames\Engine\isAnswerCorrect;
use function BrainGames\Engine\playGame;
use function BrainGames\Engine\announceResult;
use function BrainGames\Engine\startGame;

function generateRandomNumber()
{
    return random_int(1, 99);
}