#!/usr/bin/env php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

function randomNumberForPrime() {
    return random_int(1, 100);
}

function checkPrime($number) {
    $i = 2;

    while ($i < $number) {
        if ($number % $i === 0) {
            return false;
        }
        $i += 1;
    }

    return true;
}